package com.asm.common;

public enum PageType{
	USER_MANAGEMENT_PAGE, REPORT_MANAGEMENT_PAGE, Video_MANAGEMENT_PAGE,
	SITE_HOME_PAGE,SITE_LOGIN_PAGE,SITE_REGISTER_PAGE,
	SITE_CHANGE_PASSWORD_PAGE,SITE_EDIT_PROFILE_PAGE,SITE_FORGOT_PASSWORD_PAGE,
	SITE_VIDEO_DETAIL_PAGE,SITE_FAVORITE_PAGE, SITE_SHARE_PAGE, DETAIL_VIDEO_PAGE,
	ADMIN_SITE
}
